INSERT INTO BaseGameText (Tag, Text)
VALUES (
	'LOC_UNIT_BULIN_MK1_DESCRIPTION',
	'{LOC_TRAIT_CIVILIZATION_UNIT_BULIN_MK1_DESCRIPTION}[NEWLINE][NEWLINE]{LOC_UNIT_BUILDER_DESCRIPTION}'
),(
	'LOC_UNIT_BULIN_MK2_DESCRIPTION',
	'{LOC_TRAIT_CIVILIZATION_UNIT_BULIN_MK2_DESCRIPTION}[NEWLINE][NEWLINE]{LOC_UNIT_MILITARY_ENGINEER_DESCRIPTION}'
);

INSERT OR IGNORE INTO LocalizedText (Language, Tag, Text)
VALUES	('zh_Hans_CN',	'LOC_NAMED_LAKE_SENREN_BANKA1',		'五色沼湖'	),
		('zh_Hans_CN',	'LOC_NAMED_LAKE_SENREN_BANKA2',		'中禅寺湖'	),
		('zh_Hans_CN',	'LOC_NAMED_LAKE_SENREN_BANKA3',		'山中湖'		),
		('zh_Hans_CN',	'LOC_NAMED_LAKE_SENREN_BANKA4',		'知床五湖'	),
		('zh_Hans_CN',	'LOC_NAMED_LAKE_SENREN_BANKA5',		'本栖湖'		),
		('zh_Hans_CN',	'LOC_NAMED_LAKE_SENREN_BANKA6',		'田子仓湖'	),
		('zh_Hans_CN',	'LOC_NAMED_MOUNTAIN_SENREN_BANKA1',	'白山山脉'	),
		('zh_Hans_CN',	'LOC_NAMED_MOUNTAIN_SENREN_BANKA2',	'立山山脉'	),
		('zh_Hans_CN',	'LOC_NAMED_MOUNTAIN_SENREN_BANKA3',	'北岳'		),
		('zh_Hans_CN',	'LOC_NAMED_MOUNTAIN_SENREN_BANKA4',	'穂高岳'		),
		('zh_Hans_CN',	'LOC_NAMED_RIVER_SENREN_BANKA1',	'阿贺野川'	),
		('zh_Hans_CN',	'LOC_NAMED_RIVER_SENREN_BANKA2',	'四万十川'	),
		('zh_Hans_CN',	'LOC_NAMED_RIVER_SENREN_BANKA3',	'夕张川'		),
		('zh_Hans_CN',	'LOC_NAMED_RIVER_SENREN_BANKA4',	'千岁川'		),
		('zh_Hans_CN',	'LOC_NAMED_VOLCANO_SENREN_BANKA1',	'烧岳'		),
		('zh_Hans_CN',	'LOC_NAMED_VOLCANO_SENREN_BANKA2',	'诹访之濑岛'	),
		('zh_Hans_CN',	'LOC_NAMED_VOLCANO_SENREN_BANKA3',	'新燃岳'		),
		('zh_Hans_CN',	'LOC_NAMED_VOLCANO_SENREN_BANKA4',	'草津白根山'	),
		('zh_Hans_CN',	'LOC_NAMED_VOLCANO_SENREN_BANKA5',	'御岳山'		),
		('zh_Hans_CN',	'LOC_NAMED_VOLCANO_SENREN_BANKA6',	'阿苏山'		),

		('zh_Hant_HK',	'LOC_NAMED_LAKE_SENREN_BANKA1',		'五色沼湖'	),
		('zh_Hant_HK',	'LOC_NAMED_LAKE_SENREN_BANKA2',		'中禪寺湖'	),
		('zh_Hant_HK',	'LOC_NAMED_LAKE_SENREN_BANKA3',		'山中湖'		),
		('zh_Hant_HK',	'LOC_NAMED_LAKE_SENREN_BANKA4',		'知床五湖'	),
		('zh_Hant_HK',	'LOC_NAMED_LAKE_SENREN_BANKA5',		'本棲湖'		),
		('zh_Hant_HK',	'LOC_NAMED_LAKE_SENREN_BANKA6',		'田子倉湖'	),
		('zh_Hant_HK',	'LOC_NAMED_MOUNTAIN_SENREN_BANKA1',	'白山山脉'	),
		('zh_Hant_HK',	'LOC_NAMED_MOUNTAIN_SENREN_BANKA2',	'立山山脉'	),
		('zh_Hant_HK',	'LOC_NAMED_MOUNTAIN_SENREN_BANKA3',	'北嶽'		),
		('zh_Hant_HK',	'LOC_NAMED_MOUNTAIN_SENREN_BANKA4',	'穂高嶽'		),
		('zh_Hant_HK',	'LOC_NAMED_RIVER_SENREN_BANKA1',	'阿賀野川'	),
		('zh_Hant_HK',	'LOC_NAMED_RIVER_SENREN_BANKA2',	'四萬十川'	),
		('zh_Hant_HK',	'LOC_NAMED_RIVER_SENREN_BANKA3',	'夕張川'		),
		('zh_Hant_HK',	'LOC_NAMED_RIVER_SENREN_BANKA4',	'千歲川'		),
		('zh_Hant_HK',	'LOC_NAMED_VOLCANO_SENREN_BANKA1',	'燒嶽'		),
		('zh_Hant_HK',	'LOC_NAMED_VOLCANO_SENREN_BANKA2',	'諏訪之瀨島'	),
		('zh_Hant_HK',	'LOC_NAMED_VOLCANO_SENREN_BANKA3',	'新燃嶽'		),
		('zh_Hant_HK',	'LOC_NAMED_VOLCANO_SENREN_BANKA4',	'草津白根山'	),
		('zh_Hant_HK',	'LOC_NAMED_VOLCANO_SENREN_BANKA5',	'禦嶽山'		),
		('zh_Hant_HK',	'LOC_NAMED_VOLCANO_SENREN_BANKA6',	'阿蘇山'		),

		('en_US',	'LOC_NAMED_LAKE_SENREN_BANKA1',		'Goshiki-Numa'			),
		('en_US',	'LOC_NAMED_LAKE_SENREN_BANKA2',		'Lake Chuzenji'			),
		('en_US',	'LOC_NAMED_LAKE_SENREN_BANKA3',		'Lake Yamanaka'			),
		('en_US',	'LOC_NAMED_LAKE_SENREN_BANKA4',		'Lake Shiretoko'		),
		('en_US',	'LOC_NAMED_LAKE_SENREN_BANKA5',		'Lake Motosu'			),
		('en_US',	'LOC_NAMED_LAKE_SENREN_BANKA6',		'Lake Tagokura'			),
		('en_US',	'LOC_NAMED_MOUNTAIN_SENREN_BANKA1',	'Haku Mountain'			),
		('en_US',	'LOC_NAMED_MOUNTAIN_SENREN_BANKA2',	'Tateyama Mountain'		),
		('en_US',	'LOC_NAMED_MOUNTAIN_SENREN_BANKA3',	'Kita Mountain'			),
		('en_US',	'LOC_NAMED_MOUNTAIN_SENREN_BANKA4',	'Hotaka Mountain'		),
		('en_US',	'LOC_NAMED_RIVER_SENREN_BANKA1',	'Agano River'			),
		('en_US',	'LOC_NAMED_RIVER_SENREN_BANKA2',	'Shimanto River'		),
		('en_US',	'LOC_NAMED_RIVER_SENREN_BANKA3',	'Yubari River'			),
		('en_US',	'LOC_NAMED_RIVER_SENREN_BANKA4',	'Chitose River'			),
		('en_US',	'LOC_NAMED_VOLCANO_SENREN_BANKA1',	'Mount Yake'			),
		('en_US',	'LOC_NAMED_VOLCANO_SENREN_BANKA2',	'Suwanosejima'			),
		('en_US',	'LOC_NAMED_VOLCANO_SENREN_BANKA3',	'Shinmoedake'			),
		('en_US',	'LOC_NAMED_VOLCANO_SENREN_BANKA4',	'Mount Kusatsu-Shirane'	),
		('en_US',	'LOC_NAMED_VOLCANO_SENREN_BANKA5',	'Mount Ontake'			),
		('en_US',	'LOC_NAMED_VOLCANO_SENREN_BANKA6',	'Mount Aso'				);