INSERT INTO BaseGameText (Tag, Text)
VALUES (
	'LOC_UNIT_BULIN_MK1_DESCRIPTION',
	'{LOC_TRAIT_CIVILIZATION_UNIT_BULIN_MK1_DESCRIPTION}[NEWLINE][NEWLINE]{LOC_UNIT_BUILDER_DESCRIPTION}'
),(
	'LOC_UNIT_BULIN_MK2_DESCRIPTION',
	'{LOC_TRAIT_CIVILIZATION_UNIT_BULIN_MK2_DESCRIPTION}[NEWLINE][NEWLINE]{LOC_UNIT_MILITARY_ENGINEER_DESCRIPTION}'
),(
	'LOC_PEDIA_LEADERS_PAGE_LEADER_AZUR_LANE_AYANAMI_CHAPTER_CAPSULE_BODY',
	'{LOC_LOADING_INFO_LEADER_AZUR_LANE_AYANAMI}'
),(
	'LOC_PEDIA_LEADERS_PAGE_LEADER_AZUR_LANE_YUUDACHI_CHAPTER_CAPSULE_BODY',
	'{LOC_LOADING_INFO_LEADER_AZUR_LANE_YUUDACHI}'
),(
	'LOC_PEDIA_LEADERS_PAGE_LEADER_AZUR_LANE_SHIGURE_CHAPTER_CAPSULE_BODY',
	'{LOC_LOADING_INFO_LEADER_AZUR_LANE_SHIGURE}'
),(
	'LOC_PEDIA_LEADERS_PAGE_LEADER_AZUR_LANE_YUKIKAZE_CHAPTER_CAPSULE_BODY',
	'{LOC_LOADING_INFO_LEADER_AZUR_LANE_YUKIKAZE}'
);

INSERT OR IGNORE INTO LocalizedText (Language, Tag, Text)		-- Extended Japan Place Names from Senren Banka Mod
VALUES	('en_US',	'LOC_NAMED_LAKE_SENREN_BANKA1',		'Goshiki-Numa'			),
		('en_US',	'LOC_NAMED_LAKE_SENREN_BANKA2',		'Lake Chuzenji'			),
		('en_US',	'LOC_NAMED_LAKE_SENREN_BANKA3',		'Lake Yamanaka'			),
		('en_US',	'LOC_NAMED_LAKE_SENREN_BANKA4',		'Lake Shiretoko'		),
		('en_US',	'LOC_NAMED_LAKE_SENREN_BANKA5',		'Lake Motosu'			),
		('en_US',	'LOC_NAMED_LAKE_SENREN_BANKA6',		'Lake Tagokura'			),
		('en_US',	'LOC_NAMED_MOUNTAIN_SENREN_BANKA1',	'Haku Mountain'			),
		('en_US',	'LOC_NAMED_MOUNTAIN_SENREN_BANKA2',	'Tateyama Mountain'		),
		('en_US',	'LOC_NAMED_MOUNTAIN_SENREN_BANKA3',	'Kita Mountain'			),
		('en_US',	'LOC_NAMED_MOUNTAIN_SENREN_BANKA4',	'Hotaka Mountain'		),
		('en_US',	'LOC_NAMED_RIVER_SENREN_BANKA1',	'Agano River'			),
		('en_US',	'LOC_NAMED_RIVER_SENREN_BANKA2',	'Shimanto River'		),
		('en_US',	'LOC_NAMED_RIVER_SENREN_BANKA3',	'Yubari River'			),
		('en_US',	'LOC_NAMED_RIVER_SENREN_BANKA4',	'Chitose River'			),
		('en_US',	'LOC_NAMED_VOLCANO_SENREN_BANKA1',	'Mount Yake'			),
		('en_US',	'LOC_NAMED_VOLCANO_SENREN_BANKA2',	'Suwanosejima'			),
		('en_US',	'LOC_NAMED_VOLCANO_SENREN_BANKA3',	'Shinmoedake'			),
		('en_US',	'LOC_NAMED_VOLCANO_SENREN_BANKA4',	'Mount Kusatsu-Shirane'	),
		('en_US',	'LOC_NAMED_VOLCANO_SENREN_BANKA5',	'Mount Ontake'			),
		('en_US',	'LOC_NAMED_VOLCANO_SENREN_BANKA6',	'Mount Aso'				);